# Generated by Django 5.2.12 on 2026-03-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket_management', '0002_alter_ai_summarry_ticket_alter_assignment_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worklog',
            name='is_completed_worklog',
            field=models.BooleanField(default=False),
        ),
    ]
