# Generated by Django 5.2.12 on 2026-03-27 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket_management', '0003_ticket_completed_at_worklog_is_completed_worklog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
